"""empty message

Revision ID: 3978b9975f8c
Revises: 
Create Date: 2022-12-02 18:46:24.027348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3978b9975f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('image', sa.LargeBinary(length=65535), nullable=True),
    sa.Column('dig_count', sa.Integer(), nullable=True),
    sa.Column('belong_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_image_name'), 'images', ['image_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=120), nullable=True, comment='密码'),
    sa.Column('role', sa.Integer(), nullable=True, comment='用户角色'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_images_image_name'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
